### ISSUE TITLE
Starter Maven app with wrapper will not start dev mode through the dashboard

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-eclipse#152]
Generating a Maven app with the [OL starter](https://openliberty.io/start/): Java 8, EE 9.1 MP 5.0 and get the following error when starting dev mode through the dashboard:
![image](https://user-images.githubusercontent.com/26146482/187989524-f6b4c46d-aeec-4448-a08e-7471e9490c0c.png)

Eclipse version: 2022-06

However opening a terminal in Eclipse manually and running `./mvnw liberty:dev` and dev mode starts as expected.

This second part may be user error on my end, but if I delete the wrapper files from the project and try again I encounter the following error:
![image](https://user-images.githubusercontent.com/26146482/187989636-008c43b7-fb77-4154-8be5-061c45b13520.png)
However when I run `echo $PATH` in a separate Eclipse terminal the Maven /bin dir is on the path:
```
 echo $PATH
/usr/local/opt/gradle@7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kathrynkodama/Library/Maven/apache-maven-3.8.6/bin
```

**Comment by mezarin** [comment]
The issue happens because the wrapper being used by the application in question was generated prior to updates introduced by  https://issues.apache.org/jira/browse/MWRAPPER-56. This wrapper update is only few months old, and among other things it fixes the issue you are encountering with the tool's current implementation.
Until we fix this issue, you could go around this issue by removing the existing wrapper code and re-installing a recent version (mvn wrapper:wrapper)
