### ISSUE TITLE
After a clean install of Liberty Tools 0.9.0 on top of 2022-12, Eclipse LSP4Jakarta does not appear to work.

### ISSUE THREAD

**Issue by sosuisen** [OpenLiberty/liberty-tools-eclipse#374]
If I update from 0.8.0 it works fine, but on a clean install of 0.9.0 I noticed that Jakarta Servlet snippets such as servlet_doget cannot be entered using Ctrl + space.

Eclipse 2022-12

**Comment by scottkurz** [comment]
@sosuisen thanks for reporting this.    We're targeting the 2023-03 Eclipse release (4.27), and I suspect this is an area that won't work on 4.26.     

Sorry you had to learn this by trying it out and it failing.  We are trying to work within Eclipse Marketplace to see the best way to align the tool versions with versions of Eclipse.

**Comment by scottkurz** [comment]
I tried this with both the 4.26 Enterprise Java... and Java ... packages and was a bit surprised to see the problem only on my Enterprise Java install.    That is, the snippets seemed to work fine with the Eclipse IDE for Java Developers package on v4.26.

I'm going to keep this open since it'd be interesting to understand why.

**Comment by scottkurz** [comment]
I don't see this problem with Liberty Tools Eclipse 0.9.2 (soon to be published on Eclipse Marketplace).   

Again, we weren't targeting Eclipse v4.26 anyway, so we probably would be closing this anyway, but just noting as I close this issue.

Thanks for opening though.

As a general note keep in mind the snippets are activated (or deactivated) based on the specific application project's classpath.   As typical using m2e this can sometimes require you to issue a (right-click project) -> **Maven->Update Project (Alt+F5)** in order to refresh this classpath from POM dependencies.
