### ISSUE TITLE
Change file monitoring for LCLS to support custom config files

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-tools-eclipse#429]
To support [custom config files](https://github.com/OpenLiberty/liberty-language-server/issues/66), after OpenLiberty/liberty-language-server#212 goes in, the IDE client side needs to be changed to monitor the following to send to LCLS:
- all `.env` and `.properties` files - language support. Lines to change shown below:

https://github.com/OpenLiberty/liberty-tools-eclipse/blob/2fb4b6b2f3a87599c60e4571220eb593e5dd3cbe/bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml#L47-L67

- `liberty-plugin-config.xml` - watch file for changes. 
LSP protocol `workspace/didChangeWatchedFiles` possibly not supported, as per https://github.com/eclipse/lsp4e/issues/807

Not changing it shouldn't break anything, but will not have support for custom config files.

Can model after https://github.com/OpenLiberty/liberty-tools-vscode/pull/286

**Comment by scottkurz** [comment]
Thx for the details.

Since not changing this shouldn't break anything I'll file this under the 23.0.12 milestone to target for that release.

**Comment by evie-lau** [comment]
An update: implementing this change also will not break anything - so it can be done anytime.

**Comment by cherylking** [comment]
Just a quick note that I think you need to change that same file to send all XML files to LCLS, instead of just `server.xml`. LCLS will then check for the `server` root element to decide if the file gets support.

**Comment by scottkurz** [comment]
Closing this since we did the biggest piece in https://github.com/OpenLiberty/liberty-tools-eclipse/pull/460.   

We still have a smaller effort remaining: https://github.com/OpenLiberty/liberty-tools-eclipse/issues/461 to be able to react dynamically to updates to the plugin cfg.  For the time being the user will have to do some kind of restart...either of the IDE or dev mode.   Would be nice to have doc but if we're going to fix anyway maybe it's not as much of a priority.
