### ISSUE TITLE
null pointer exception when using liberty tools

### ISSUE THREAD

**Issue by denemedenemedenemedene** [OpenLiberty/liberty-tools-eclipse#430]
**Describe the bug**  
null pointer exception when using liberty tools 23.0.7 plugin in  eclipse to create a new server

**Steps to Reproduce**  
open eclipse 2023.06 from windows machine instal open liberty tools from marketplace 
try to create a new open liberty server from servers menu give open liberty directory/wlp click finish

**Expected behavior**  
create open liberty server in eclipse

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: 
 - openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
 - server.xml configuration NO SERVER XML
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by scottkurz** [comment]
In the newer **Liberty Tools** we take a different approach than the older Liberty/WebSphere Eclipse IDE tooling.   Rather than providing Liberty implementations for constructs like the **Target runtime** to support things like the **Publish** operation and management through the **Servers** view, as in the older [Liberty Developer Tools](https://marketplace.eclipse.org/content/ibm-liberty-developer-tools) or [WebSphere Developer Tools](https://www.ibm.com/docs/en/wasdtfe?topic=installing-websphere-application-server-developer-tools-eclipse) features, we use a different approach.

For **Liberty Tools**, we assume the use of a Maven or Gradle project.   Compilation is performed against normal Maven/Gradle dependencies and the Liberty Maven and Gradle plugins manage installation of the Liberty runtime and deployment of your application to this runtime.  

So, if you'd like to use the new **Liberty Tools**, please see our [User Guide](https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/docs/user-guide.md) to get started.

If you want to continue to use the older approach, see the "Liberty Developer Tools" linked above.

And feel free to reach out on our [Gitter](https://gitter.im/OpenLiberty/developer-experience) channel to discuss.

(I'm going to close this issue for now.)
